WIP: relocate 4.3 portlet-definition schema to a separate package
Attempt to address an issue in uPortal 5.0 wherein a portlet-definition that uses the 4.3 schema and contains the following fragment fails to import:

```
    <lifecycle>
        <approved user="system">2015-11-06T12:48:19.717-07:00</approved>
        <published user="system">2015-11-06T12:48:19.717-07:00</published>
    </lifecycle>
```

The original error observed in uPortal import:

```
java.lang.RuntimeException: Failed to map provided XML to portal data
	at org.apereo.portal.io.xml.JaxbPortalDataHandlerService.unmarshallData(JaxbPortalDataHandlerService.java:863)
	at org.apereo.portal.io.xml.JaxbPortalDataHandlerService.importOrUpgradeData(JaxbPortalDataHandlerService.java:794)
	at org.apereo.portal.io.xml.JaxbPortalDataHandlerService.importData(JaxbPortalDataHandlerService.java:734)
	at org.apereo.portal.io.xml.JaxbPortalDataHandlerService.importOrUpgradeData(JaxbPortalDataHandlerService.java:839)
	at org.apereo.portal.io.xml.JaxbPortalDataHandlerService.importData(JaxbPortalDataHandlerService.java:734)
	at org.apereo.portal.io.xml.JaxbPortalDataHandlerService.importData(JaxbPortalDataHandlerService.java:767)
	at org.apereo.portal.io.xml.JaxbPortalDataHandlerService$2.callWithoutResult(JaxbPortalDataHandlerService.java:626)
	at org.apereo.portal.concurrency.CallableWithoutResult.call(CallableWithoutResult.java:24)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.oxm.UnmarshallingFailureException: JAXB unmarshalling exception; nested exception is javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; cvc-complex-type.2.4.a: Invalid content was found starting with element 'lifecycle'. One of '{"https://source.jasig.org/schemas/uportal/io/portlet-definition":lifecycle, "https://source.jasig.org/schemas/uportal/io/portlet-definition":category, "https://source.jasig.org/schemas/uportal/io/portlet-definition":group, "https://source.jasig.org/schemas/uportal/io/portlet-definition":user, "https://source.jasig.org/schemas/uportal/io/portlet-definition":permissions, "https://source.jasig.org/schemas/uportal/io/portlet-definition":parameter, "https://source.jasig.org/schemas/uportal/io/portlet-definition":portlet-preference}' is expected.]
	at org.springframework.oxm.jaxb.Jaxb2Marshaller.convertJaxbException(Jaxb2Marshaller.java:911)
	at org.springframework.oxm.jaxb.Jaxb2Marshaller.unmarshal(Jaxb2Marshaller.java:784)
	at org.springframework.oxm.jaxb.Jaxb2Marshaller.unmarshal(Jaxb2Marshaller.java:753)
	at org.apereo.portal.io.xml.JaxbPortalDataHandlerService.unmarshallData(JaxbPortalDataHandlerService.java:861)
	... 11 more
Caused by: javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; cvc-complex-type.2.4.a: Invalid content was found starting with element 'lifecycle'. One of '{"https://source.jasig.org/schemas/uportal/io/portlet-definition":lifecycle, "https://source.jasig.org/schemas/uportal/io/portlet-definition":category, "https://source.jasig.org/schemas/uportal/io/portlet-definition":group, "https://source.jasig.org/schemas/uportal/io/portlet-definition":user, "https://source.jasig.org/schemas/uportal/io/portlet-definition":permissions, "https://source.jasig.org/schemas/uportal/io/portlet-definition":parameter, "https://source.jasig.org/schemas/uportal/io/portlet-definition":portlet-preference}' is expected.]
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.handleStreamException(UnmarshallerImpl.java:483)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:463)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:435)
	at org.springframework.oxm.jaxb.Jaxb2Marshaller.unmarshalStaxSource(Jaxb2Marshaller.java:800)
	at org.springframework.oxm.jaxb.Jaxb2Marshaller.unmarshal(Jaxb2Marshaller.java:766)
	... 13 more
Caused by: org.xml.sax.SAXParseException; cvc-complex-type.2.4.a: Invalid content was found starting with element 'lifecycle'. One of '{"https://source.jasig.org/schemas/uportal/io/portlet-definition":lifecycle, "https://source.jasig.org/schemas/uportal/io/portlet-definition":category, "https://source.jasig.org/schemas/uportal/io/portlet-definition":group, "https://source.jasig.org/schemas/uportal/io/portlet-definition":user, "https://source.jasig.org/schemas/uportal/io/portlet-definition":permissions, "https://source.jasig.org/schemas/uportal/io/portlet-definition":parameter, "https://source.jasig.org/schemas/uportal/io/portlet-definition":portlet-preference}' is expected.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:452)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3230)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1790)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:740)
	at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorHandlerImpl.startElement(ValidatorHandlerImpl.java:570)
	at com.sun.xml.bind.v2.runtime.unmarshaller.ValidatingUnmarshaller.startElement(ValidatingUnmarshaller.java:101)
	at com.sun.xml.bind.v2.runtime.unmarshaller.InterningXmlVisitor.startElement(InterningXmlVisitor.java:75)
	at com.sun.xml.bind.v2.runtime.unmarshaller.StAXEventConnector.handleStartElement(StAXEventConnector.java:261)
	at com.sun.xml.bind.v2.runtime.unmarshaller.StAXEventConnector.bridge(StAXEventConnector.java:130)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:460)
	... 16 more
```